### ISSUE TITLE
error: unexpected argument '--mapdir' found

### ISSUE THREAD

**Issue by danielwcho** [vmware-labs/webassembly-language-runtimes#132]
### Describe the bug

when I try to run the code in the picture, I get 

```
error: unexpected argument '--mapdir' found

  tip: to pass '--mapdir' as a value, use '-- --mapdir'

Usage: wasmtime run [OPTIONS] <WASM>...
```

### Reproduction steps

1. Checked my wasmtime version (wasmtime-cli 22.0.0 (761f044ef 2024-06-20)
2. I am pretty sure every files are in the correct directory

### Expected behavior

The 🐇 woke up with a smile.
The 🌅 was shining on his face.
A 🥕 was waiting for him on the table.
He will put on his 👖 and get out of the 🏠 for a walk.

### Additional context

<img width="1183" alt="Screenshot 2024-07-08 at 5 40 45 PM" src="https://github.com/vmware-labs/webassembly-language-runtimes/assets/171643426/82c1929e-3a5b-4319-8405-4e5f93cab7d3">

**Comment by betaboon** [comment]
i just stumbled upon the same issue.

it seems like a while ago `wasmtime` [redesigned their cli interface](https://github.com/bytecodealliance/wasmtime/pull/6925)

`--mapdir GUEST_DIR::HOST_DIR` has been replaced by `--dir HOST_DIR::GUEST_DIR`.

so in your case, instead of 
```
wasmtime run \
  --mapdir /workdir::$PWD/workdir \
  --mapdir /::$PWD/tmp/unpacked \
  tmp/unpacked/bin/python-3.12.0.wasm
```

this should do the trick:
```
wasmtime run \
  --dir $PWD/workdir::/workdir \
  --dir $PWD/tmp/unpacked::/ \
  tmp/unpacked/bin/python-3.12.0.wasm
```

**Comment by danielwcho** [comment]
Thanks!
