### ISSUE TITLE
Build libraries separately for reuse and publishing

### ISSUE THREAD

**Issue by ereslibre** [vmware-labs/webassembly-language-runtimes#47]
Right now, libraries are built as a dependency of another project, such as the PHP, Python or Ruby builds.

Make it easier and possible to build these libraries as entities of their own, so that it's easier to work and, soon, publish these libraries as well.

**Comment by assambar** [comment]
More things to do

- [ ] Build libsqlite
- [ ] Publish builds of libuuid, libsqlite, zlib
- [ ] Create docs/examples on how to use them

**Comment by assambar** [comment]
This is addressed by https://github.com/vmware-labs/webassembly-language-runtimes/pull/74.
All currently built libraries were release subsequently.
