### ISSUE TITLE
Tag a python docker image that isn't wasmedge specific

### ISSUE THREAD

**Issue by codefromthecrypt** [vmware-labs/webassembly-language-runtimes#51]
ghcr.io/vmware-labs/python-wasm:3.11.1-latest is wasmedge specific, and has signatures incompatible with WASI. This makes it impossible to use in other runtimes including what's supported by crun (wasmer and wasmtime) as well what isn't yet (wazero)

Can you re-publish this so that both compatible and the wasmedge vendor specific images exist. I understand wasmedge is important, but it would be nice for others to easily re-use your work and docker is easier than extracting zips.

**Comment by codefromthecrypt** [comment]
By the way, I tried the non-wasmedge build and failed. It would be helpful to create CI to prove they work, as it is easy to get things like paths wrong.

**Comment by assambar** [comment]
@codefromthecrypt thanks for the input! Putting this on the plan!

> By the way, I tried the non-wasmedge build and failed. It would be helpful to create CI to prove they work, as it is easy to get things like paths wrong.

Totally agree about a CI, that's on the roadmap. If possible could you share what failed? Is it not working at all or was it a non-obvious configuration issue (since you mention paths)?

**Comment by codefromthecrypt** [comment]
I was trying to build a docker image out of it, but python didn't start fully due to some encoding error. The image itself was a little complicated due to having to download and unzip stuff, and prefer to not set that up again right now.

when there's a portable image basically I'll try again which is something like this, just python instead of a glorified hollo world https://github.com/tetratelabs/wazero/pull/1099#issuecomment-1418111204

**Comment by assambar** [comment]
> I was trying to build a docker image out of it, but python didn't start fully due to some encoding error. The image itself was a little complicated due to having to download and unzip stuff, and prefer to not set that up again right now.

Got it. The encoding error is caused by the missing standard library. When you build the docker image you also need to add the `usr` folder from the release in `/usr`. As is done here - https://github.com/vmware-labs/webassembly-language-runtimes/blob/main/images/python/Dockerfile.
We'll try to also offer a fat binary via wasi-vfs so you won't need to do this in future.

> when there's a portable image basically I'll try again which is something like this, just python instead of a glorified hollo world [tetratelabs/wazero#1099 (comment)](https://github.com/tetratelabs/wazero/pull/1099#issuecomment-1418111204)

I will ping you when we publish one.

**Comment by codefromthecrypt** [comment]
thanks for the tips and also interesting about wasi-vfs as indeed that would be easy for anything built-in!

**Comment by assambar** [comment]
New images published:
 - `ghcr.io/vmware-labs/python-wasm:3.11.1` - WASI compliant
 - `ghcr.io/vmware-labs/python-wasm:3.11.1-wasmedge` - WasmEdge compliant

**Comment by codefromthecrypt** [comment]
great. I'll give these a go shortly (pun intended)

**Comment by codefromthecrypt** [comment]
@assambar thanks to @evacchi this is confirmed working (albeit 1.0.1 not 1.0.0 😊) https://github.com/tetratelabs/wazero/releases/tag/v1.0.1
