### ISSUE TITLE
Any data on runtime memory usage?

### ISSUE THREAD

**Issue by shafqatevo** [vmware-labs/webassembly-language-runtimes#65]
Hi, great work!

Is there any data anywhere on the runtime memory usage in kb/mb of just the language runtimes for say a no-op or hello world program?

**Comment by assambar** [comment]
Not yet. We're following the "make it work", "make it stable", "make it fast" approach.
And I'd say we're still in the "make it stable" phase. 
We definitely intend to have some benchmarking and numbers and all, but not in the immediate future.

**Comment by shafqatevo** [comment]
Thanks @assambar ! Makes sense…
